### 1.import pandas library
### 2.create a dataframe obj from a dict of lists of your own choice(other than population) 
### 3.Add another column on the above object and insert values.  
### 4.create a dataframe obj from a series obj of your own choice.
### 5.create a dataframe obj from the above series obj(Qno.4) after assigning a value for
		 name attribute.

In [1]:
import pandas as pd

In [3]:
d2 = {'name':['ravi','tom','pandas','numpy'],'rno':[11,22,33,44],'marks':[20,33,44,77]}

In [4]:
from pandas import DataFrame as df

f1 = df(d2)

In [5]:
f1

marks    name  rno
0     20    ravi   11
1     33     tom   22
2     44  pandas   33
3     77   numpy   44

In [6]:
f1['new']=0

In [7]:
f1

marks    name  rno  new
0     20    ravi   11    0
1     33     tom   22    0
2     44  pandas   33    0
3     77   numpy   44    0

In [8]:
from pandas import Series as se

s1 = se(list('abcd'))
s1

0    a
1    b
2    c
3    d
dtype: object

In [10]:
fs = df(s1)
fs

0
0  a
1  b
2  c
3  d

### 6.create a dataframe object from a numpy 2D array by giving values for columns and index 
		of your own choice. 

In [23]:
import numpy as np


s = np.array(range(20)).reshape((4,5))
print s,s.shape

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)


In [25]:
f2m = df(s,index=list('abcd'),columns=list('12345'))
f2m

1   2   3   4   5
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19

### 	7.create a nested dictionary to store employee details like empno,empname and salary.
	  create a dataframe from this dict.

### 8.create a series object to contain designations of the above employees, assign 'desig' as 
		the name to this series object.

### 9.Add the above series object to the dataframe object and the column name should be the same 
		as series name.

### 10.Create two series objects with
		values (1,2 ... 6) and (11,22 ... 66),  
		indices (a,b,c,d,e,f) and (d,e,f,x,y,z) respectively.
		Add the two series objects, the result should contain 9 nonzero values.	
		(use reindex)

In [28]:
s1 = se(range(1,7))
s1.index = list('abcdef')
print s1
s2 = se([11,22,33,44,55,66])
s2.index = list('defxyz')
print s2

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64
d    11
e    22
f    33
x    44
y    55
z    66
dtype: int64
