* 1. open a python interpreter
* 2. import numpy
* 3. create a 1D array having 5 elements (integers) using array method
* 4. do 3 using arange  	 
* 5. create a 3 dimensional array containing 1s(integers), there should be 40 members
* 6. print the total number of elements (size) for the above array
* 7. Check and explain the difference between array and asarray
* 8. Create an identity mtrix of a given specification.
* 9. Create an array containing 0s inheriting shape from the array created in Q.No.5
* 10.Print the size,shape,dimensions and datatype of all the above arrays. 

In [1]:
import numpy as np

In [5]:
a3  = np.array([1,2,3,4,5])
a4 = np.arange(1,6)

a3


array([1, 2, 3, 4, 5])

In [6]:
a4

array([1, 2, 3, 4, 5])

In [11]:
a5 = np.ones((2,5,4))
a5.size

40

In [21]:
t2 = np.ones(5).astype(np.int)
print 't2 : ',id(t2)

a17 = np.array(t2)
print 'a17 : ',id(a17)
a27 = np.asarray(t2)
print 'a17 : ',id(a27)

print t2 is a17
print t2 is a27

t2 :  140206197239040
a17 :  140206197238480
a17 :  140206197239040
False
True


In [24]:
a8 = np.eye(4).astype(int)
a8

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [27]:
a9 = np.zeros_like(a5)
print a9
a9 is a5

[[[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]
  [ 0.  0.  0.  0.]]]


False

In [30]:
print "Shape : ",a9.shape
print "Size : ",a9.size
print "Dimen : ",a9.ndim

Shape :  (2, 5, 4)
Size :  40
Dimen :  3
