## 1. Using the Taxi environment in Open AI , reset the environment.
## 2. Using random moves pickup a passenger and drop the passenger at his desired                   
##        location. Find out how many moves had to 



# * color maynot display properly : git visualization 

In [18]:
import gym
env = gym.make("Taxi-v2")
state = env.reset() ## reset to new state (random)
print "State",state
env.render()

State 228
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+



In [19]:
reward = 0
count = 0
while( reward != 20):
    action = env.action_space.sample()
    s,reward,done,info = env.step(action)
    count +=1
    
env.render()
print "total moves required :",count

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
total moves required : 76


## 3. Implement the Q Learning Algorith on the Taxi environment.


In [20]:
print env.observation_space.n, env.action_space.n

500 6


In [21]:
import numpy as np
#initialize q matrix = 0
Q = np.zeros((env.observation_space.n, env.action_space.n))
print Q

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 ..., 
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


###  * Q(state, action) = R(state, action) + Gamma * Max[Q(next state, all actions)]

In [33]:
env.reset()

gamma = 0.8 
episodes = 1000
    

In [36]:
reward = 0
count = 0
for e in range(episodes):
    
    state = env.reset();
    reward = 0
    count = 0
    while( reward != 20):
        action = np.argmax(Q[state])
        newstate,reward,done,info = env.step(action)
        Q[state,action] = reward + gamma * np.max(Q[newstate]); #update Q table
        state = newstate
        count +=1
        
    if(e % 50 == 0):
        print e,": total moves required :",count
    


0 : total moves required : 13
50 : total moves required : 14
100 : total moves required : 11
150 : total moves required : 8
200 : total moves required : 12
250 : total moves required : 16
300 : total moves required : 11
350 : total moves required : 13
400 : total moves required : 8
450 : total moves required : 13
500 : total moves required : 12
550 : total moves required : 13
600 : total moves required : 13
650 : total moves required : 11
700 : total moves required : 18
750 : total moves required : 19
800 : total moves required : 8
850 : total moves required : 13
900 : total moves required : 13
950 : total moves required : 14


In [37]:
print Q

[[  0.         0.         0.         0.         0.         0.      ]
 [ -3.951424  -3.951424  -3.951424  -3.951424  17.020096 -10.      ]
 [ -2.952     -2.952     -2.952     -2.952     29.4064   -10.      ]
 ..., 
 [ -3.3616     5.24      -2.952     -2.952    -10.       -10.      ]
 [ -3.68928   -3.68928   -3.68928   -3.3616   -10.       -10.      ]
 [ -1.8       -1.8       -1.8       27.8      -10.       -10.      ]]


## 4. Solution by learned model

In [39]:
action_seq = {0:'down',1:'up',2:'right',3:'left',4:'pick-up',5:'drop-off'}

{0: 'down', 1: 'up', 2: 'right', 3: 'left', 4: 'pick-up', 5: 'drop-off'}

In [40]:
state = env.reset();
env.render()
reward = 0
count = 0
solution =[]
while( reward != 20):
    action = np.argmax(Q[state])
    newstate,reward,done,info = env.step(action)
    state = newstate
    solution.append(action_seq[action])
    count +=1
        
print ": total moves required :",count
print "Solution :\n",solution

+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+

: total moves required : 13
Solution :
['left', 'down', 'down', 'right', 'down', 'down', 'pick-up', 'up', 'up', 'up', 'up', 'right', 'drop-off']


## 5. Render any  3 environments in OpenAi gym.