### 0.import pandas 
### 1.Create a (4,4)2D array  consisting of integers.
### 2.Create a masked array from the above array by making numbers which are divisible by 3 as invalid values.
### 3.Create a dataframe from the above masked array.
### 4.Create a series of your own choice and do reindexing by exploring ffill,bfill,nearest etc
### 5.Create a Dataframe object of your own choice and do reindexing.


In [1]:
import pandas as pd
import numpy as np

In [2]:
a2 = np.array(range(1,17)).reshape(4,4)
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
mask_a3 = np.ma.masked_array(a2,mask=a2%3 == 0)
mask_a3

masked_array(data =
 [[1 2 -- 4]
 [5 -- 7 8]
 [-- 10 11 --]
 [13 14 -- 16]],
             mask =
 [[False False  True False]
 [False  True False False]
 [ True False False  True]
 [False False  True False]],
       fill_value = 999999)

In [4]:
mask_a3.mask

array([[False, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True],
       [False, False,  True, False]], dtype=bool)

In [5]:
from pandas import DataFrame as df

dfm3 =df(mask_a3) 
dfm3

0     1     2     3
0   1.0   2.0   NaN   4.0
1   5.0   NaN   7.0   8.0
2   NaN  10.0  11.0   NaN
3  13.0  14.0   NaN  16.0

In [6]:
from pandas import Series as se

se1 = se(range(5),index=list('abcde'))
se1

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [7]:
se1.reindex(list('edcab'))

e    4
d    3
c    2
a    0
b    1
dtype: int64

In [8]:
x =se1.reindex(list('abcdef'))
x

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
f    NaN
dtype: float64

In [9]:
fx =se1.reindex(list('abcdef'),method='ffill')
fx

a    0
b    1
c    2
d    3
e    4
f    4
dtype: int64

In [10]:
# backward fill
bx =se1.reindex(list('abcdfe'),method='bfill')
bx

a    0.0
b    1.0
c    2.0
d    3.0
f    NaN
e    4.0
dtype: float64

In [11]:
# nearest
bx =se1.reindex(list('abcdfe'),method='nearest')
bx

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [12]:
# reindexing on DataFrame
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
dfa2 = df(a2,columns='c1 c2 c3 c4'.split(),index=list('abcd'))
dfa2

c1  c2  c3  c4
a   1   2   3   4
b   5   6   7   8
c   9  10  11  12
d  13  14  15  16

In [14]:
dfa2.reindex(list('acdb')) # Equivalent to dfa2.reindex(index = list('acdb'))

c1  c2  c3  c4
a   1   2   3   4
c   9  10  11  12
d  13  14  15  16
b   5   6   7   8

In [15]:
dfa2.reindex(columns = 'c2 c1 c3 c4'.split())

c2  c1  c3  c4
a   2   1   3   4
b   6   5   7   8
c  10   9  11  12
d  14  13  15  16

### 6.Create a (4,4)2D array  consisting of integers.
### 7.create a dataframe object from the above array by making c1,c2,c3,c4 as column indices and r1,r2,r3,r4 as row indices.
####   7.1 Using integer based indexing print the very first element(row 0, column 0) as a scalar,as a series,and as a dataframe.
####   7.2 do 2.1 using label based indexing
####   7.3 Print last two rows and columns

In [16]:
a2 = np.array(range(1,17)).reshape(4,4)
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
df2d = df(a2,index='r1 r2 r3 r4'.split(), columns='c1 c2 c3 c4'.split())
df2d

c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16

In [28]:
#as scalar
res = df2d.iloc[0,0]
print res
type(res)

1


numpy.int64

In [29]:
#as series
res = df2d.iloc[0:1,0] ## or df2d.iloc[[0],0]
print res
type(res)

r1    1
Name: c1, dtype: int64


pandas.core.series.Series

In [30]:
#as dataframe
res = df2d.iloc[0:1,0:1] ## ## or df2d.iloc[[0],[0]]
print res
type(res)

    c1
r1   1


pandas.core.frame.DataFrame

In [41]:
# label based using loc
res = df2d.loc['r1','c1']
print res
print type(res)

res1 = df2d.loc[['r1'],'c1']
print res1
print type(res1)

res2 = df2d.loc[['r1'],['c1']]
print res2
print type(res2)



1
<type 'numpy.int64'>
r1    1
Name: c1, dtype: int64
<class 'pandas.core.series.Series'>
    c1
r1   1
<class 'pandas.core.frame.DataFrame'>


### 	8.Create another (4,4)2D array  consisting of integers, with c1,c2,c5,c6 as column indices and r3,r4,r5,r6 as row indices
####     Create a dataframe from this array and do the following,
####       a) add the two dataframes(QNo.7) using '+' operator,withoou any NaN in the result
####       b) add the two dataframes using 'add' method,withoou any NaN in the result

In [50]:
dataf = df(a2,index='r3 r4 r5 r6'.split(), columns='c1 c2 c5 c6'.split())
print df2d,'\n\n',dataf

    c1  c2  c3  c4
r1   1   2   3   4
r2   5   6   7   8
r3   9  10  11  12
r4  13  14  15  16 

    c1  c2  c5  c6
r3   1   2   3   4
r4   5   6   7   8
r5   9  10  11  12
r6  13  14  15  16


In [51]:
dataf.add(df2d,fill_value=0)

c1    c2    c3    c4    c5    c6
r1   1.0   2.0   3.0   4.0   NaN   NaN
r2   5.0   6.0   7.0   8.0   NaN   NaN
r3  10.0  12.0  11.0  12.0   3.0   4.0
r4  18.0  20.0  15.0  16.0   7.0   8.0
r5   9.0  10.0   NaN   NaN  11.0  12.0
r6  13.0  14.0   NaN   NaN  15.0  16.0

### 9.Create DataFrame obj(shape 3,4) and from that create two Series objs(one for axis 0,other for axis 1)
		perform subtraction operation for both cases(along the two axes)